method_name: fedavg

# #model parameters
model_init_params:
  #for resnet
  KD: false
  projection: false
  #for vim
  pretrained: null

  #for resnet_for_merge
  depth: 22
  widen_factor: 2
  dropout_rate: 0