method_name: feddelta
hyperparams:
  theta : 0.2
  gamma : 0.5
  amplifier : 0.1
  damping : 2
  eps: 1e-5

# #model parameters
model_init_params:
  #for resnet
  KD: false
  projection: false
  #for vim
  pretrained: null

  #for resnet_for_merge
  depth: 22
  widen_factor: 2
  dropout_rate: 0