method_name: feddecorr
hyperparams:
  mu : 0.1

# #model parameters
model_init_params:
  #for resnet
  KD: true
  projection: false
  #for vim
  pretrained: null
  #for resnet_for_merge
  depth: 22
  widen_factor: 2
  dropout_rate: 0