method_name: fedlora
hyperparams:
  M: 3
  start_round: 150

# #model parameters
model_init_params:
  #for resnet
  KD: false
  projection: false
  #for vim
  pretrained: null
  #for MLP
  #for resnet_for_merge
  depth: 22
  widen_factor: 2
  dropout_rate: 0