method_name: moon

hyperparams:
  mu: 1
  temp : 0.5

model_init_params:
  #for resnet
  KD: True
  projection: true
  #for vim
  pretrained: null
  #for resnet_for_merge
  depth: 22
  widen_factor: 2
  dropout_rate: 0